name: mapsapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.10.1
  location: ^7.0.1

  flutter_bloc: ^9.1.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  sliding_up_panel: ^2.0.0+1
  socket_io_client: ^3.1.2
  web_socket_channel: ^3.0.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/car.png
    - assets/map_styles/aubergine_map_style.json
    - assets/map_styles/night_map_style.json
